export const SEARCH_NAVBAR_REQUEST = 'SEARCH_NAVBAR_REQUEST'
export const SEARCH_NAVBAR_SUCCESS = 'SEARCH_NAVBAR_SUCCESS'
export const SEARCH_NAVBAR_FAILURE = 'SEARCH_NAVBAR_FAILURE'

export const CLEAR_NAVBAR_SEARCH = 'CLEAR_NAVBAR_SEARCH'

export const ADVANCE_SEARCH_PAGE = 'ADVANCE_SEARCH_PAGE'
export const RESET_SEARCH_PAGE = 'RESET_SEARCH_PAGE'

export const REQUEST_SEARCH_FETCH = 'REQUEST_SEARCH_FETCH'
export const SUCCESS_SEARCH_FETCH = 'SUCCESS_SEARCH_FETCH'
export const FAILURE_SEARCH_FETCH = 'FAILURE_SEARCH_FETCH'

export const REQUEST_SEARCH_POST = 'REQUEST_SEARCH_POST'
export const SUCCESS_SEARCH_POST = 'SUCCESS_SEARCH_POST'
export const FAILURE_SEARCH_POST = 'FAILURE_SEARCH_POST'

export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const RESET_PAGE = 'RESET_PAGE'