export const FETCHING_POSTS = 'FETCHING_POSTS'
export const SUCCESS_POSTS = 'SUCCESS_POSTS'

export const FETCHING_PROFILE_POSTS = 'FETCHING_PROFILE_POSTS'
export const SUCCESS_PROFILE_POSTS = 'SUCCESS_PROFILE_POSTS'
export const FAILURE_PROFILE_POSTS = 'FAILURE_PROFILE_POSTS'

export const RESET_PAGE = 'RESET_PAGE'
export const ADVANCE_PAGE = 'ADVANCE_PAGE'

export const RESET_PROFILE_PAGE = 'RESET_PROFILE_PAGE'
export const ADVANCE_PROFILE_PAGE = 'ADVANCE_PROFILE_PAGE'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_REDUX = 'DELETE_POST_REDUX'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
export const EDIT_POST_REDUX = 'EDIT_POST_REDUX'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE'

export const POST_FAVORITE_REQUEST = 'POST_FAVORITE_REQUEST'
export const POST_FAVORITE_REDUX = 'POST_FAVORITE_REDUX'
export const POST_FAVORITE_SUCCESS = 'POST_FAVORITE_SUCCESS'
export const POST_FAVORITE_FAILURE = 'POST_FAVOIRTE_FAILURE'

export const POST_UNFAVORITE_REQUEST = 'POST_UNFAVORITE_REQUEST'
export const POST_UNFAVORITE_REDUX = 'POST_UNFAVORITE_REDUX'
export const POST_UNFAVORITE_SUCCESS = 'POST_UNFAVORITE_SUCCESS'
export const POST_UNFAVORITE_FAILURE = 'POST_UNFAVORITE_FAILURE'

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'

export const ADVANCE_COMMENT_PAGE = 'ADVANCE_COMMENT_PAGE'

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST'
export const POST_COMMENT_REDUX = 'POST_COMMENT_REDUX'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_REDUX = 'DELETE_COMMENT_REDUX'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE'

export const CLEAR_POSTS = 'CLEAR_POSTS'