export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAILURE_LOGIN = 'FAILURE_LOGIN'

export const LOGOUT = 'LOGOUT'

export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST'
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS'
export const FETCH_RESOURCES_CONTINUE = 'FETCH_RESOURCE_CONTINUE'
export const FETCH_RESOURCES_FAILURE = 'FETCH_RESOURCES_FAILURE'

export const PUT_CHANGE_INFORMATION = 'PUT_CHANGE_INFORMATION'
export const SUCCESS_CHANGE_INFORMATION = 'SUCCESS_CHANGE_INFORMATION'
export const FAILURE_CHANGE_INFORMATION = 'FAILURE_CHANGE_INFORMATION'

export const PUT_CHANGE_PROFILE = 'PUT_CHANGE_PROFILE'
export const SUCCESS_CHANGE_PROFILE = 'SUCCESS_CHANGE_PROFILE'
export const FAILURE_CHANGE_PROFILE = 'FAILURE_CHANGE_PROFILE'

export const REMOVE_RESPONSE = 'REMOVE_RESPONSE'
export const REMOVE_IMAGE_RESPONSE = 'REMOVE_IMAGE_RESPONSE'