export const REQUEST_USER_PROFILE = 'REQUEST_USER_PROFILE'
export const SUCCESS_USER_PROFILE = 'SUCCESS_USER_PROFILE'
export const FAILURE_USER_PROFILE = 'FAILURE_USER_PROFILE'

export const CLEAR_PROFILE = 'CLEAR_PROFILE'

export const REQUEST_FOLLOW_PROFILE = 'REQUEST_FOLLOW_PROFILE'
export const REDUX_FOLLOW_PROFILE = 'REDUX_FOLLOW_PROFILE'
export const SUCCESS_FOLLOW_PROFILE = 'SUCCESS_FOLLOW_PROFILE'
export const FAILURE_FOLLOW_PROFILE = 'FAILURE_FOLLOW_PROFILE'

export const REQUEST_UNFOLLOW_PROFILE = 'REQUEST_UNFOLLOW_PROFILE'
export const REDUX_UNFOLLOW_PROFILE = 'REDUX_UNFOLLOW_PROFILE'
export const SUCCESS_UNFOLLOW_PROFILE = 'REQUEST_UNFOLLOW_PROFILE'
export const FAILURE_UNFOLLOW_PROFILE = 'FAILURE_UNFOLLOW_PROFILE'